### ISSUE TITLE
Gymnopedie & AGONY [Beta] hosted on discord, links expired.

### ISSUE THREAD

**Issue by fennecr** [eternalUnion/AngryLevels#1]
When attempting to download these levels (and potentially others) in game, you'll receive a "network error", after further inspection, it looks like the files are hosted on discord's CDN, which no longer keeps file permanently. Trying to download manually shows that the files have been removed.
Consider moving these files to another filehost?

**Comment by eternalUnion** [comment]
Makers of these levels did not want to update them so the links stayed. Levels may be removed from the list soon.
